laser:
  verbose: false
  window_width: 50.0
  window_length: 20.0
  threshold: 2.5
control:
  kpt: 1.0
  kit: 0.1
  krt: 1.0
  kvt: 5.0
  ramp_time: 5.0
  max_lin_vel: 1.0
topics:
  line_pcl: "bisector_pcl"
  filtered_line_pcl: "filtered_bisector_pcl"
  line_coeffs: "bisector_coeffs"
  filtered_line_coeffs: "filtered_bisector_coeffs"
  laser_scan: "scan"
  cmd_vel: "car_command"
tfs:
  base_link: "base_link"
  laser_link: "hokuyo_link"
